# Generated by Django 4.1.4 on 2023-01-28 14:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_rename_description_leadership_description_or_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='description_or_role',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
